//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_GUI.ServiceIngreso {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceIngreso.WebServiceIngresoSoap")]
    public interface WebServiceIngresoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarIngresoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarIngresoService(Capa_GUI.ServiceIngreso.Ingreso ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarIngresoService", ReplyAction="*")]
        System.Threading.Tasks.Task insertarIngresoServiceAsync(Capa_GUI.ServiceIngreso.Ingreso ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarIngresoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarIngresoService(Capa_GUI.ServiceIngreso.Ingreso ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarIngresoService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarIngresoServiceAsync(Capa_GUI.ServiceIngreso.Ingreso ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarIngresoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarIngresoService(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarIngresoService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarIngresoServiceAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarIngresoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet consultarIngresoService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarIngresoService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> consultarIngresoServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaIngresoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Capa_GUI.ServiceIngreso.Ingreso buscaIngresoService(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaIngresoService", ReplyAction="*")]
        System.Threading.Tasks.Task<Capa_GUI.ServiceIngreso.Ingreso> buscaIngresoServiceAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionIngresoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Capa_GUI.ServiceIngreso.Ingreso posicionIngresoService(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionIngresoService", ReplyAction="*")]
        System.Threading.Tasks.Task<Capa_GUI.ServiceIngreso.Ingreso> posicionIngresoServiceAsync(int fila);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ingreso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private System.DateTime fechaField;
        
        private string prioridadField;
        
        private int paciente_idField;
        
        private int medico_cargo_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Prioridad {
            get {
                return this.prioridadField;
            }
            set {
                this.prioridadField = value;
                this.RaisePropertyChanged("Prioridad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Paciente_id {
            get {
                return this.paciente_idField;
            }
            set {
                this.paciente_idField = value;
                this.RaisePropertyChanged("Paciente_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Medico_cargo_id {
            get {
                return this.medico_cargo_idField;
            }
            set {
                this.medico_cargo_idField = value;
                this.RaisePropertyChanged("Medico_cargo_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceIngresoSoapChannel : Capa_GUI.ServiceIngreso.WebServiceIngresoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceIngresoSoapClient : System.ServiceModel.ClientBase<Capa_GUI.ServiceIngreso.WebServiceIngresoSoap>, Capa_GUI.ServiceIngreso.WebServiceIngresoSoap {
        
        public WebServiceIngresoSoapClient() {
        }
        
        public WebServiceIngresoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceIngresoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceIngresoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceIngresoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarIngresoService(Capa_GUI.ServiceIngreso.Ingreso ingreso) {
            base.Channel.insertarIngresoService(ingreso);
        }
        
        public System.Threading.Tasks.Task insertarIngresoServiceAsync(Capa_GUI.ServiceIngreso.Ingreso ingreso) {
            return base.Channel.insertarIngresoServiceAsync(ingreso);
        }
        
        public void actualizarIngresoService(Capa_GUI.ServiceIngreso.Ingreso ingreso) {
            base.Channel.actualizarIngresoService(ingreso);
        }
        
        public System.Threading.Tasks.Task actualizarIngresoServiceAsync(Capa_GUI.ServiceIngreso.Ingreso ingreso) {
            return base.Channel.actualizarIngresoServiceAsync(ingreso);
        }
        
        public void eliminarIngresoService(int id) {
            base.Channel.eliminarIngresoService(id);
        }
        
        public System.Threading.Tasks.Task eliminarIngresoServiceAsync(int id) {
            return base.Channel.eliminarIngresoServiceAsync(id);
        }
        
        public System.Data.DataSet consultarIngresoService() {
            return base.Channel.consultarIngresoService();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> consultarIngresoServiceAsync() {
            return base.Channel.consultarIngresoServiceAsync();
        }
        
        public Capa_GUI.ServiceIngreso.Ingreso buscaIngresoService(int id) {
            return base.Channel.buscaIngresoService(id);
        }
        
        public System.Threading.Tasks.Task<Capa_GUI.ServiceIngreso.Ingreso> buscaIngresoServiceAsync(int id) {
            return base.Channel.buscaIngresoServiceAsync(id);
        }
        
        public Capa_GUI.ServiceIngreso.Ingreso posicionIngresoService(int fila) {
            return base.Channel.posicionIngresoService(fila);
        }
        
        public System.Threading.Tasks.Task<Capa_GUI.ServiceIngreso.Ingreso> posicionIngresoServiceAsync(int fila) {
            return base.Channel.posicionIngresoServiceAsync(fila);
        }
    }
}
