//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_GUI.ServiceMedico {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMedico.WebServiceMedicoCargoSoap")]
    public interface WebServiceMedicoCargoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarMedicoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarMedicoService(Capa_GUI.ServiceMedico.Medico_cargo medico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarMedicoService", ReplyAction="*")]
        System.Threading.Tasks.Task insertarMedicoServiceAsync(Capa_GUI.ServiceMedico.Medico_cargo medico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarMedicoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarMedicoService(Capa_GUI.ServiceMedico.Medico_cargo medico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarMedicoService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarMedicoServiceAsync(Capa_GUI.ServiceMedico.Medico_cargo medico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarMedicoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarMedicoService(string medico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarMedicoService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarMedicoServiceAsync(string medico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarMedicoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet consultarMedicoService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarMedicoService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> consultarMedicoServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaMedicoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Capa_GUI.ServiceMedico.Medico_cargo buscaMedicoService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaMedicoService", ReplyAction="*")]
        System.Threading.Tasks.Task<Capa_GUI.ServiceMedico.Medico_cargo> buscaMedicoServiceAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionMedicoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Capa_GUI.ServiceMedico.Medico_cargo posicionMedicoService(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionMedicoService", ReplyAction="*")]
        System.Threading.Tasks.Task<Capa_GUI.ServiceMedico.Medico_cargo> posicionMedicoServiceAsync(int fila);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Medico_cargo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string rutField;
        
        private string claveField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string especialidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("Especialidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMedicoCargoSoapChannel : Capa_GUI.ServiceMedico.WebServiceMedicoCargoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMedicoCargoSoapClient : System.ServiceModel.ClientBase<Capa_GUI.ServiceMedico.WebServiceMedicoCargoSoap>, Capa_GUI.ServiceMedico.WebServiceMedicoCargoSoap {
        
        public WebServiceMedicoCargoSoapClient() {
        }
        
        public WebServiceMedicoCargoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMedicoCargoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMedicoCargoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMedicoCargoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarMedicoService(Capa_GUI.ServiceMedico.Medico_cargo medico) {
            base.Channel.insertarMedicoService(medico);
        }
        
        public System.Threading.Tasks.Task insertarMedicoServiceAsync(Capa_GUI.ServiceMedico.Medico_cargo medico) {
            return base.Channel.insertarMedicoServiceAsync(medico);
        }
        
        public void actualizarMedicoService(Capa_GUI.ServiceMedico.Medico_cargo medico) {
            base.Channel.actualizarMedicoService(medico);
        }
        
        public System.Threading.Tasks.Task actualizarMedicoServiceAsync(Capa_GUI.ServiceMedico.Medico_cargo medico) {
            return base.Channel.actualizarMedicoServiceAsync(medico);
        }
        
        public void eliminarMedicoService(string medico) {
            base.Channel.eliminarMedicoService(medico);
        }
        
        public System.Threading.Tasks.Task eliminarMedicoServiceAsync(string medico) {
            return base.Channel.eliminarMedicoServiceAsync(medico);
        }
        
        public System.Data.DataSet consultarMedicoService() {
            return base.Channel.consultarMedicoService();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> consultarMedicoServiceAsync() {
            return base.Channel.consultarMedicoServiceAsync();
        }
        
        public Capa_GUI.ServiceMedico.Medico_cargo buscaMedicoService(string rut) {
            return base.Channel.buscaMedicoService(rut);
        }
        
        public System.Threading.Tasks.Task<Capa_GUI.ServiceMedico.Medico_cargo> buscaMedicoServiceAsync(string rut) {
            return base.Channel.buscaMedicoServiceAsync(rut);
        }
        
        public Capa_GUI.ServiceMedico.Medico_cargo posicionMedicoService(int fila) {
            return base.Channel.posicionMedicoService(fila);
        }
        
        public System.Threading.Tasks.Task<Capa_GUI.ServiceMedico.Medico_cargo> posicionMedicoServiceAsync(int fila) {
            return base.Channel.posicionMedicoServiceAsync(fila);
        }
    }
}
