//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_GUI.ServicePaciente {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePaciente.WebServicePacienteSoap")]
    public interface WebServicePacienteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarPacienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarPacienteService(Capa_GUI.ServicePaciente.Paciente paciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarPacienteService", ReplyAction="*")]
        System.Threading.Tasks.Task insertarPacienteServiceAsync(Capa_GUI.ServicePaciente.Paciente paciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarPacienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarPacienteService(Capa_GUI.ServicePaciente.Paciente paciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarPacienteService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarPacienteServiceAsync(Capa_GUI.ServicePaciente.Paciente paciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarPacienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarPacienteService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarPacienteService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarPacienteServiceAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarPacienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet consultarPacienteService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarPacienteService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> consultarPacienteServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarPacienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Capa_GUI.ServicePaciente.Paciente buscarPacienteService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarPacienteService", ReplyAction="*")]
        System.Threading.Tasks.Task<Capa_GUI.ServicePaciente.Paciente> buscarPacienteServiceAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionPacienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Capa_GUI.ServicePaciente.Paciente posicionPacienteService(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionPacienteService", ReplyAction="*")]
        System.Threading.Tasks.Task<Capa_GUI.ServicePaciente.Paciente> posicionPacienteServiceAsync(int fila);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Paciente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string rutField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string antecedentesField;
        
        private string stock_productosField;
        
        private string disponibilidadField;
        
        private string epicrisisField;
        
        private string telefonoField;
        
        private int tutor_idField;
        
        private string tutor_nombreField;
        
        private int ubicacion_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Antecedentes {
            get {
                return this.antecedentesField;
            }
            set {
                this.antecedentesField = value;
                this.RaisePropertyChanged("Antecedentes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Stock_productos {
            get {
                return this.stock_productosField;
            }
            set {
                this.stock_productosField = value;
                this.RaisePropertyChanged("Stock_productos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Disponibilidad {
            get {
                return this.disponibilidadField;
            }
            set {
                this.disponibilidadField = value;
                this.RaisePropertyChanged("Disponibilidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Epicrisis {
            get {
                return this.epicrisisField;
            }
            set {
                this.epicrisisField = value;
                this.RaisePropertyChanged("Epicrisis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Tutor_id {
            get {
                return this.tutor_idField;
            }
            set {
                this.tutor_idField = value;
                this.RaisePropertyChanged("Tutor_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Tutor_nombre {
            get {
                return this.tutor_nombreField;
            }
            set {
                this.tutor_nombreField = value;
                this.RaisePropertyChanged("Tutor_nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Ubicacion_id {
            get {
                return this.ubicacion_idField;
            }
            set {
                this.ubicacion_idField = value;
                this.RaisePropertyChanged("Ubicacion_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePacienteSoapChannel : Capa_GUI.ServicePaciente.WebServicePacienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePacienteSoapClient : System.ServiceModel.ClientBase<Capa_GUI.ServicePaciente.WebServicePacienteSoap>, Capa_GUI.ServicePaciente.WebServicePacienteSoap {
        
        public WebServicePacienteSoapClient() {
        }
        
        public WebServicePacienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePacienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePacienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePacienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarPacienteService(Capa_GUI.ServicePaciente.Paciente paciente) {
            base.Channel.insertarPacienteService(paciente);
        }
        
        public System.Threading.Tasks.Task insertarPacienteServiceAsync(Capa_GUI.ServicePaciente.Paciente paciente) {
            return base.Channel.insertarPacienteServiceAsync(paciente);
        }
        
        public void actualizarPacienteService(Capa_GUI.ServicePaciente.Paciente paciente) {
            base.Channel.actualizarPacienteService(paciente);
        }
        
        public System.Threading.Tasks.Task actualizarPacienteServiceAsync(Capa_GUI.ServicePaciente.Paciente paciente) {
            return base.Channel.actualizarPacienteServiceAsync(paciente);
        }
        
        public void eliminarPacienteService(string rut) {
            base.Channel.eliminarPacienteService(rut);
        }
        
        public System.Threading.Tasks.Task eliminarPacienteServiceAsync(string rut) {
            return base.Channel.eliminarPacienteServiceAsync(rut);
        }
        
        public System.Data.DataSet consultarPacienteService() {
            return base.Channel.consultarPacienteService();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> consultarPacienteServiceAsync() {
            return base.Channel.consultarPacienteServiceAsync();
        }
        
        public Capa_GUI.ServicePaciente.Paciente buscarPacienteService(string rut) {
            return base.Channel.buscarPacienteService(rut);
        }
        
        public System.Threading.Tasks.Task<Capa_GUI.ServicePaciente.Paciente> buscarPacienteServiceAsync(string rut) {
            return base.Channel.buscarPacienteServiceAsync(rut);
        }
        
        public Capa_GUI.ServicePaciente.Paciente posicionPacienteService(int fila) {
            return base.Channel.posicionPacienteService(fila);
        }
        
        public System.Threading.Tasks.Task<Capa_GUI.ServicePaciente.Paciente> posicionPacienteServiceAsync(int fila) {
            return base.Channel.posicionPacienteServiceAsync(fila);
        }
    }
}
