//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_GUI.ServiceTutor {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTutor.WebServiceTutorSoap")]
    public interface WebServiceTutorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarTutorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarTutorService(Capa_GUI.ServiceTutor.Tutor tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarTutorService", ReplyAction="*")]
        System.Threading.Tasks.Task insertarTutorServiceAsync(Capa_GUI.ServiceTutor.Tutor tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarTutorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarTutorService(Capa_GUI.ServiceTutor.Tutor tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarTutorService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarTutorServiceAsync(Capa_GUI.ServiceTutor.Tutor tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarTutorServce", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarTutorServce(string tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarTutorServce", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarTutorServceAsync(string tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarTutorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet consultarTutorService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarTutorService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> consultarTutorServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaTutorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Capa_GUI.ServiceTutor.Tutor buscaTutorService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaTutorService", ReplyAction="*")]
        System.Threading.Tasks.Task<Capa_GUI.ServiceTutor.Tutor> buscaTutorServiceAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionTutorService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Capa_GUI.ServiceTutor.Tutor posicionTutorService(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionTutorService", ReplyAction="*")]
        System.Threading.Tasks.Task<Capa_GUI.ServiceTutor.Tutor> posicionTutorServiceAsync(int fila);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Tutor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string rutField;
        
        private string claveField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string telefonoField;
        
        private string correoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("Correo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTutorSoapChannel : Capa_GUI.ServiceTutor.WebServiceTutorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTutorSoapClient : System.ServiceModel.ClientBase<Capa_GUI.ServiceTutor.WebServiceTutorSoap>, Capa_GUI.ServiceTutor.WebServiceTutorSoap {
        
        public WebServiceTutorSoapClient() {
        }
        
        public WebServiceTutorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTutorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTutorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTutorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarTutorService(Capa_GUI.ServiceTutor.Tutor tutor) {
            base.Channel.insertarTutorService(tutor);
        }
        
        public System.Threading.Tasks.Task insertarTutorServiceAsync(Capa_GUI.ServiceTutor.Tutor tutor) {
            return base.Channel.insertarTutorServiceAsync(tutor);
        }
        
        public void actualizarTutorService(Capa_GUI.ServiceTutor.Tutor tutor) {
            base.Channel.actualizarTutorService(tutor);
        }
        
        public System.Threading.Tasks.Task actualizarTutorServiceAsync(Capa_GUI.ServiceTutor.Tutor tutor) {
            return base.Channel.actualizarTutorServiceAsync(tutor);
        }
        
        public void eliminarTutorServce(string tutor) {
            base.Channel.eliminarTutorServce(tutor);
        }
        
        public System.Threading.Tasks.Task eliminarTutorServceAsync(string tutor) {
            return base.Channel.eliminarTutorServceAsync(tutor);
        }
        
        public System.Data.DataSet consultarTutorService() {
            return base.Channel.consultarTutorService();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> consultarTutorServiceAsync() {
            return base.Channel.consultarTutorServiceAsync();
        }
        
        public Capa_GUI.ServiceTutor.Tutor buscaTutorService(string rut) {
            return base.Channel.buscaTutorService(rut);
        }
        
        public System.Threading.Tasks.Task<Capa_GUI.ServiceTutor.Tutor> buscaTutorServiceAsync(string rut) {
            return base.Channel.buscaTutorServiceAsync(rut);
        }
        
        public Capa_GUI.ServiceTutor.Tutor posicionTutorService(int fila) {
            return base.Channel.posicionTutorService(fila);
        }
        
        public System.Threading.Tasks.Task<Capa_GUI.ServiceTutor.Tutor> posicionTutorServiceAsync(int fila) {
            return base.Channel.posicionTutorServiceAsync(fila);
        }
    }
}
