//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_GUI.ServiceTutor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tutor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Tutor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTutor.WebServiceTutorSoap")]
    public interface WebServiceTutorSoap {
        
        // CODEGEN: Generating message contract since element name tutor from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarTutorService", ReplyAction="*")]
        Capa_GUI.ServiceTutor.insertarTutorServiceResponse insertarTutorService(Capa_GUI.ServiceTutor.insertarTutorServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarTutorService", ReplyAction="*")]
        System.Threading.Tasks.Task<Capa_GUI.ServiceTutor.insertarTutorServiceResponse> insertarTutorServiceAsync(Capa_GUI.ServiceTutor.insertarTutorServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarTutorServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarTutorService", Namespace="http://tempuri.org/", Order=0)]
        public Capa_GUI.ServiceTutor.insertarTutorServiceRequestBody Body;
        
        public insertarTutorServiceRequest() {
        }
        
        public insertarTutorServiceRequest(Capa_GUI.ServiceTutor.insertarTutorServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarTutorServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Capa_GUI.ServiceTutor.Tutor tutor;
        
        public insertarTutorServiceRequestBody() {
        }
        
        public insertarTutorServiceRequestBody(Capa_GUI.ServiceTutor.Tutor tutor) {
            this.tutor = tutor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarTutorServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarTutorServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Capa_GUI.ServiceTutor.insertarTutorServiceResponseBody Body;
        
        public insertarTutorServiceResponse() {
        }
        
        public insertarTutorServiceResponse(Capa_GUI.ServiceTutor.insertarTutorServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarTutorServiceResponseBody {
        
        public insertarTutorServiceResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTutorSoapChannel : Capa_GUI.ServiceTutor.WebServiceTutorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTutorSoapClient : System.ServiceModel.ClientBase<Capa_GUI.ServiceTutor.WebServiceTutorSoap>, Capa_GUI.ServiceTutor.WebServiceTutorSoap {
        
        public WebServiceTutorSoapClient() {
        }
        
        public WebServiceTutorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTutorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTutorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTutorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Capa_GUI.ServiceTutor.insertarTutorServiceResponse Capa_GUI.ServiceTutor.WebServiceTutorSoap.insertarTutorService(Capa_GUI.ServiceTutor.insertarTutorServiceRequest request) {
            return base.Channel.insertarTutorService(request);
        }
        
        public void insertarTutorService(Capa_GUI.ServiceTutor.Tutor tutor) {
            Capa_GUI.ServiceTutor.insertarTutorServiceRequest inValue = new Capa_GUI.ServiceTutor.insertarTutorServiceRequest();
            inValue.Body = new Capa_GUI.ServiceTutor.insertarTutorServiceRequestBody();
            inValue.Body.tutor = tutor;
            Capa_GUI.ServiceTutor.insertarTutorServiceResponse retVal = ((Capa_GUI.ServiceTutor.WebServiceTutorSoap)(this)).insertarTutorService(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Capa_GUI.ServiceTutor.insertarTutorServiceResponse> Capa_GUI.ServiceTutor.WebServiceTutorSoap.insertarTutorServiceAsync(Capa_GUI.ServiceTutor.insertarTutorServiceRequest request) {
            return base.Channel.insertarTutorServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Capa_GUI.ServiceTutor.insertarTutorServiceResponse> insertarTutorServiceAsync(Capa_GUI.ServiceTutor.Tutor tutor) {
            Capa_GUI.ServiceTutor.insertarTutorServiceRequest inValue = new Capa_GUI.ServiceTutor.insertarTutorServiceRequest();
            inValue.Body = new Capa_GUI.ServiceTutor.insertarTutorServiceRequestBody();
            inValue.Body.tutor = tutor;
            return ((Capa_GUI.ServiceTutor.WebServiceTutorSoap)(this)).insertarTutorServiceAsync(inValue);
        }
    }
}
