//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_GUI.ServiceAtencion {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAtencion.WebServiceAtencionSoap")]
    public interface WebServiceAtencionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarAtencionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarAtencionService(Capa_GUI.ServiceAtencion.Atencion atencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarAtencionService", ReplyAction="*")]
        System.Threading.Tasks.Task insertarAtencionServiceAsync(Capa_GUI.ServiceAtencion.Atencion atencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarAtencionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarAtencionService(Capa_GUI.ServiceAtencion.Atencion atencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarAtencionService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarAtencionServiceAsync(Capa_GUI.ServiceAtencion.Atencion atencion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarAtencionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarAtencionService(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarAtencionService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarAtencionServiceAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarAtencionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet consultarAtencionService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarAtencionService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> consultarAtencionServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaAtencionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Capa_GUI.ServiceAtencion.Atencion buscaAtencionService(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaAtencionService", ReplyAction="*")]
        System.Threading.Tasks.Task<Capa_GUI.ServiceAtencion.Atencion> buscaAtencionServiceAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionAtencionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Capa_GUI.ServiceAtencion.Atencion posicionAtencionService(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionAtencionService", ReplyAction="*")]
        System.Threading.Tasks.Task<Capa_GUI.ServiceAtencion.Atencion> posicionAtencionServiceAsync(int fila);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Atencion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private System.DateTime fechaField;
        
        private string detalleField;
        
        private int ingreso_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
                this.RaisePropertyChanged("Detalle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Ingreso_id {
            get {
                return this.ingreso_idField;
            }
            set {
                this.ingreso_idField = value;
                this.RaisePropertyChanged("Ingreso_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceAtencionSoapChannel : Capa_GUI.ServiceAtencion.WebServiceAtencionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceAtencionSoapClient : System.ServiceModel.ClientBase<Capa_GUI.ServiceAtencion.WebServiceAtencionSoap>, Capa_GUI.ServiceAtencion.WebServiceAtencionSoap {
        
        public WebServiceAtencionSoapClient() {
        }
        
        public WebServiceAtencionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceAtencionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAtencionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAtencionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarAtencionService(Capa_GUI.ServiceAtencion.Atencion atencion) {
            base.Channel.insertarAtencionService(atencion);
        }
        
        public System.Threading.Tasks.Task insertarAtencionServiceAsync(Capa_GUI.ServiceAtencion.Atencion atencion) {
            return base.Channel.insertarAtencionServiceAsync(atencion);
        }
        
        public void actualizarAtencionService(Capa_GUI.ServiceAtencion.Atencion atencion) {
            base.Channel.actualizarAtencionService(atencion);
        }
        
        public System.Threading.Tasks.Task actualizarAtencionServiceAsync(Capa_GUI.ServiceAtencion.Atencion atencion) {
            return base.Channel.actualizarAtencionServiceAsync(atencion);
        }
        
        public void eliminarAtencionService(int id) {
            base.Channel.eliminarAtencionService(id);
        }
        
        public System.Threading.Tasks.Task eliminarAtencionServiceAsync(int id) {
            return base.Channel.eliminarAtencionServiceAsync(id);
        }
        
        public System.Data.DataSet consultarAtencionService() {
            return base.Channel.consultarAtencionService();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> consultarAtencionServiceAsync() {
            return base.Channel.consultarAtencionServiceAsync();
        }
        
        public Capa_GUI.ServiceAtencion.Atencion buscaAtencionService(int id) {
            return base.Channel.buscaAtencionService(id);
        }
        
        public System.Threading.Tasks.Task<Capa_GUI.ServiceAtencion.Atencion> buscaAtencionServiceAsync(int id) {
            return base.Channel.buscaAtencionServiceAsync(id);
        }
        
        public Capa_GUI.ServiceAtencion.Atencion posicionAtencionService(int fila) {
            return base.Channel.posicionAtencionService(fila);
        }
        
        public System.Threading.Tasks.Task<Capa_GUI.ServiceAtencion.Atencion> posicionAtencionServiceAsync(int fila) {
            return base.Channel.posicionAtencionServiceAsync(fila);
        }
    }
}
