//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_GUI.ServiceUbicacion {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUbicacion.WebServiceUbicacionSoap")]
    public interface WebServiceUbicacionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarUbicacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarUbicacionService(Capa_GUI.ServiceUbicacion.Ubicacion ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarUbicacionService", ReplyAction="*")]
        System.Threading.Tasks.Task insertarUbicacionServiceAsync(Capa_GUI.ServiceUbicacion.Ubicacion ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarUbicacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarUbicacionService(Capa_GUI.ServiceUbicacion.Ubicacion ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarUbicacionService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarUbicacionServiceAsync(Capa_GUI.ServiceUbicacion.Ubicacion ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarUbicacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarUbicacionService(string area);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarUbicacionService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarUbicacionServiceAsync(string area);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarUbicacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarUbicacionService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarUbicacionService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ConsultarUbicacionServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaUbicacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Capa_GUI.ServiceUbicacion.Ubicacion buscaUbicacionService(string area);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscaUbicacionService", ReplyAction="*")]
        System.Threading.Tasks.Task<Capa_GUI.ServiceUbicacion.Ubicacion> buscaUbicacionServiceAsync(string area);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionUbicacionService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Capa_GUI.ServiceUbicacion.Ubicacion posicionUbicacionService(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionUbicacionService", ReplyAction="*")]
        System.Threading.Tasks.Task<Capa_GUI.ServiceUbicacion.Ubicacion> posicionUbicacionServiceAsync(int fila);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ubicacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string areaField;
        
        private int camasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Camas {
            get {
                return this.camasField;
            }
            set {
                this.camasField = value;
                this.RaisePropertyChanged("Camas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUbicacionSoapChannel : Capa_GUI.ServiceUbicacion.WebServiceUbicacionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUbicacionSoapClient : System.ServiceModel.ClientBase<Capa_GUI.ServiceUbicacion.WebServiceUbicacionSoap>, Capa_GUI.ServiceUbicacion.WebServiceUbicacionSoap {
        
        public WebServiceUbicacionSoapClient() {
        }
        
        public WebServiceUbicacionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUbicacionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUbicacionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUbicacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarUbicacionService(Capa_GUI.ServiceUbicacion.Ubicacion ubicacion) {
            base.Channel.insertarUbicacionService(ubicacion);
        }
        
        public System.Threading.Tasks.Task insertarUbicacionServiceAsync(Capa_GUI.ServiceUbicacion.Ubicacion ubicacion) {
            return base.Channel.insertarUbicacionServiceAsync(ubicacion);
        }
        
        public void actualizarUbicacionService(Capa_GUI.ServiceUbicacion.Ubicacion ubicacion) {
            base.Channel.actualizarUbicacionService(ubicacion);
        }
        
        public System.Threading.Tasks.Task actualizarUbicacionServiceAsync(Capa_GUI.ServiceUbicacion.Ubicacion ubicacion) {
            return base.Channel.actualizarUbicacionServiceAsync(ubicacion);
        }
        
        public void eliminarUbicacionService(string area) {
            base.Channel.eliminarUbicacionService(area);
        }
        
        public System.Threading.Tasks.Task eliminarUbicacionServiceAsync(string area) {
            return base.Channel.eliminarUbicacionServiceAsync(area);
        }
        
        public System.Data.DataSet ConsultarUbicacionService() {
            return base.Channel.ConsultarUbicacionService();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ConsultarUbicacionServiceAsync() {
            return base.Channel.ConsultarUbicacionServiceAsync();
        }
        
        public Capa_GUI.ServiceUbicacion.Ubicacion buscaUbicacionService(string area) {
            return base.Channel.buscaUbicacionService(area);
        }
        
        public System.Threading.Tasks.Task<Capa_GUI.ServiceUbicacion.Ubicacion> buscaUbicacionServiceAsync(string area) {
            return base.Channel.buscaUbicacionServiceAsync(area);
        }
        
        public Capa_GUI.ServiceUbicacion.Ubicacion posicionUbicacionService(int fila) {
            return base.Channel.posicionUbicacionService(fila);
        }
        
        public System.Threading.Tasks.Task<Capa_GUI.ServiceUbicacion.Ubicacion> posicionUbicacionServiceAsync(int fila) {
            return base.Channel.posicionUbicacionServiceAsync(fila);
        }
    }
}
